FROM arm32v7/openjdk:11.0-jre-slim

LABEL autor="Chris Wohlbrecht"

COPY qemu-arm-static /usr/bin/


ENV TZ=Europe/Berlin

ARG JAR_FILE=target/menu-service.jar
ADD ${JAR_FILE} menu-service.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/menu-service.jar"]
