-- MySQL Script generated by MySQL Workbench
-- Fr 11 Okt 2019 08:56:24 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema menu_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema menu_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS menu_service;
USE menu_service;

-- -----------------------------------------------------
-- Table menu_service.week
-- -----------------------------------------------------
CREATE SEQUENCE menu_service.sequence_week
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS menu_service.week
(
    id          BIGINT NOT NULL,
    week_number INT    NOT NULL,
    year        INT    NOT NULL,
    start_date  DATE   NULL,
    end_date    DATE   NULL,
    PRIMARY KEY (id)
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table menu_service.unit_of_measure
-- -----------------------------------------------------
CREATE SEQUENCE menu_service.sequence_unit_of_measure
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS menu_service.unit_of_measure
(
    id   BIGINT      NOT NULL,
    name VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table menu_service.ingredient
-- -----------------------------------------------------
CREATE SEQUENCE menu_service.sequence_ingredient
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS menu_service.ingredient
(
    id                 BIGINT      NOT NULL,
    name               VARCHAR(45) NOT NULL,
    external_id        VARCHAR(45) NULL,
    unit_of_measure_id BIGINT      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_unit_of_measure1
        FOREIGN KEY (unit_of_measure_id)
            REFERENCES menu_service.unit_of_measure (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE INDEX fk_product_unit_of_measure1_idx ON menu_service.ingredient (unit_of_measure_id ASC);


-- -----------------------------------------------------
-- Table menu_service.menu
-- -----------------------------------------------------
CREATE SEQUENCE menu_service.sequence_menu
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE TABLE IF NOT EXISTS menu_service.menu
(
    id   BIGINT      NOT NULL,
    name VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table menu_service.week_has_menu
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS menu_service.week_has_menu
(
    week_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (week_id, menu_id),
    CONSTRAINT fk_week_has_menu_week
        FOREIGN KEY (week_id)
            REFERENCES menu_service.week (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT fk_week_has_menu_menu1
        FOREIGN KEY (menu_id)
            REFERENCES menu_service.menu (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE INDEX fk_week_has_menu_menu1_idx ON menu_service.week_has_menu (menu_id ASC);

CREATE INDEX fk_week_has_menu_week_idx ON menu_service.week_has_menu (week_id ASC);


-- -----------------------------------------------------
-- Table menu_service.menu_has_ingredient
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS menu_service.menu_has_ingredient
(
    menu_id       BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    amount        FLOAT  NULL,
    PRIMARY KEY (menu_id, ingredient_id),
    CONSTRAINT fk_menu_has_ingredient_menu1
        FOREIGN KEY (menu_id)
            REFERENCES menu_service.menu (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT fk_menu_has_ingredient_ingredient1
        FOREIGN KEY (ingredient_id)
            REFERENCES menu_service.ingredient (id)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = MyISAM
    COLLATE = utf8_general_ci;

CREATE INDEX fk_menu_has_ingredient_ingredient1_idx ON menu_service.menu_has_ingredient (ingredient_id ASC);

CREATE INDEX fk_menu_has_ingredient_menu1_idx ON menu_service.menu_has_ingredient (menu_id ASC);

